import { Teko } from "next/font/google";
import "./globals.css";
import "animate.css";

const teko = Teko({
  weight: ["300", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Jajan Panglima",
  description: "Generated by syafar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://raw.githubusercontent.com/Syafar44/assets/main/assets/image/LOGO%20JAJAN%20Panglima-01.png"
          type="image/png"
          sizes="16x16"
        />
      </head>
      <body className={teko.className}>{children}</body>
    </html>
  );
}
