import { Teko } from "next/font/google";
import "./globals.css";
import "animate.css";

const teko = Teko({
  weight: ["300", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Jajan Panglima",
  description: "Generated by syafar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={teko.className}>{children}</body>
    </html>
  );
}
